### ISSUE TITLE
Start and End Delimiter

### ISSUE THREAD

**Issue by RichardRaue** [xushengs/flutter_markdown_latex#5]
Hi,

thank you for this lib. I am trying to parse a GPT response with your lib. Unfortunately, GPT returns LaTeX code with a start and end delimiter that are NOT the same. So LateX block starts with '\[' and ends with '\]', inline LaTeX starts with '\(' and ends with '\)'. Is there a way to add different delimiters for start and end of a LaTeX string? Thank you in advance!

**Comment by xushengs** [comment]
I took a look, and it seems that GPT can return a variety of formats, including the current $ format. Let me try to fix it.

**Comment by xushengs** [comment]
> Hi,
> 
> thank you for this lib. I am trying to parse a GPT response with your lib. Unfortunately, GPT returns LaTeX code with a start and end delimiter that are NOT the same. So LateX block starts with '[' and ends with ']', inline LaTeX starts with '(' and ends with ')'. Is there a way to add different delimiters for start and end of a LaTeX string? Thank you in advance!

Try this:
```
  flutter_markdown_latex: 
    git: 
      url: git@github.com:xushengs/flutter_markdown_latex.git
      ref: dev
```
